"""Initial Phase 1 Schema

Revision ID: f0c883b5e4dd
Revises: 
Create Date: 2026-09-09 13:37:33.275768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c883b5e4dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=True)
    op.create_table('student_subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_subjects_student_id'), 'student_subjects', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_subjects_subject_id'), 'student_subjects', ['subject_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('parent_topic_id', sa.String(length=36), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_parent_topic_id'), 'topics', ['parent_topic_id'], unique=False)
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=False)
    op.create_index(op.f('ix_topics_subject_id'), 'topics', ['subject_id'], unique=False)
    op.create_table('academic_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_subject_id', sa.String(length=36), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path_or_storage_reference', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_subject_id'], ['student_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_materials_student_subject_id'), 'academic_materials', ['student_subject_id'], unique=False)
    op.create_table('prerequisites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('prerequisite_topic_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('topic_id != prerequisite_topic_id', name='ck_no_self_prerequisite'),
    sa.ForeignKeyConstraint(['prerequisite_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'prerequisite_topic_id', name='uq_topic_prerequisite')
    )
    op.create_index(op.f('ix_prerequisites_prerequisite_topic_id'), 'prerequisites', ['prerequisite_topic_id'], unique=False)
    op.create_index(op.f('ix_prerequisites_topic_id'), 'prerequisites', ['topic_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_subject_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_subject_id'], ['student_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_student_subject_id'), 'units', ['student_subject_id'], unique=False)
    op.create_table('syllabus_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabus_topics_topic_id'), 'syllabus_topics', ['topic_id'], unique=False)
    op.create_index(op.f('ix_syllabus_topics_unit_id'), 'syllabus_topics', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syllabus_topics_unit_id'), table_name='syllabus_topics')
    op.drop_index(op.f('ix_syllabus_topics_topic_id'), table_name='syllabus_topics')
    op.drop_table('syllabus_topics')
    op.drop_index(op.f('ix_units_student_subject_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_prerequisites_topic_id'), table_name='prerequisites')
    op.drop_index(op.f('ix_prerequisites_prerequisite_topic_id'), table_name='prerequisites')
    op.drop_table('prerequisites')
    op.drop_index(op.f('ix_academic_materials_student_subject_id'), table_name='academic_materials')
    op.drop_table('academic_materials')
    op.drop_index(op.f('ix_topics_subject_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_index(op.f('ix_topics_parent_topic_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_student_subjects_subject_id'), table_name='student_subjects')
    op.drop_index(op.f('ix_student_subjects_student_id'), table_name='student_subjects')
    op.drop_table('student_subjects')
    op.drop_index(op.f('ix_subjects_slug'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('students')
    # ### end Alembic commands ###
